# Website settings
url: "https://www.ismailbay.at/writing"

# Internal nav
nav:
  all: "/"
  tags: "/tags"

# Bio settings
name: "Ismail Bay"
description: "not motivated to blog, but still trying though ..."
thumbnail_path: "profile-photos/ismailbay-medium.jpg"
website_repo_url: "https://github.com/ismailbay/ismailbay.github.io"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/of_ismailbay"
    label: "Twitter"
    icon: "twitter-square"
    username: "@brikis98"
  linkedin:
    url: "https://www.linkedin.com/in/ismailbay"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/ismailbay/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:noone@example.com"
    label: "Email"
    value: "noone@example.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/page:num"
permalink: "/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Vienna'
repository: ismailbay/ismailbay.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
