# Website settings
url: "https://www.ismailbay.at/writing"

# Internal nav
nav:
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"

# Bio settings
name: "Ismail Bay"
description: "not motivated to blog, but still trying though ..."
thumbnail_path: "profile-photos/ismailbay-medium.jpg"
hello_startup_url: "https://www.hello-startup.net/"
website_repo_url: "https://github.com/ismailbay/ismailbay.github.io"
atomic_squirrel_url: "https://www.atomic-squirrel.net/"
gruntwork_url: "https://www.gruntwork.io/"
terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/of_ismailbay"
    label: "Twitter"
    icon: "twitter-square"
    username: "@brikis98"
  linkedin:
    url: "https://www.linkedin.com/in/ismailbay"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/ismailbay/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:noone@example.com"
    label: "Email"
    value: "noone@example.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Vienna'
repository: ismailbay/ismailbay.github.io

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
